### ISSUE TITLE
[QUESTION] Would it be possible to update the vrep_interface_move_kuka.py example?

### ISSUE THREAD

**Issue by marcos-pereira** [dqrobotics/python-examples#2]
Hi @mmmarinho ,

As discussed on issue dqrobotics/python#14 , the example [vrep_interface_move_kuka.py](https://github.com/dqrobotics/python-examples/blob/master/vrep_interface/vrep_interface_move_kuka.py) is importing the DQ_LinearAlgebra in a wrong way which does not run.

Instead of using 
```
from dqrobotics.utils.DQ_LinearAlgebra import *
```
it should use
```
from dqrobotics.utils import *
```

Would it be possible to update the example?

Thanks,

Marcos

**Comment by mmmarinho** [comment]
Hello, @marcos-pereira, @bvadorno 

Thanks for considering the pull request. In preparation for it, I transferred the issue to the python-examples issue tracker.

**Comment by marcos-pereira** [comment]
Hi @mmmarinho ,

Thanks for the hints for issue [dqrobotics/python#16](https://github.com/dqrobotics/python/issues/16). After reading the example [vrep_interface_move_kuka_and_youbot.py](https://github.com/dqrobotics/python-examples/blob/master/vrep_interface/vrep_interface_move_kuka_and_youbot.py#L1), it seems simple to fix the problem. 

However, while fixing issue [dqrobotics/python#16](https://github.com/dqrobotics/python/issues/16), I found another issue related to fixing this [current issue](https://github.com/dqrobotics/python-examples/issues/2). The KukaLw4VrepRobot is missing on the [interfaces/vrep/robots](https://github.com/dqrobotics/cpp-interface-vrep/tree/master/src/dqrobotics/interfaces/vrep/robots).

Should I also open (and solve it) a issue to create a DQ_VrepRobot for KukaLw4 on [interfaces/vrep/robots](https://github.com/dqrobotics/cpp-interface-vrep/tree/master/src/dqrobotics/interfaces/vrep/robots) to update the [vrep_interface_move_kuka.py](https://github.com/dqrobotics/python-examples/blob/master/vrep_interface/vrep_interface_move_kuka.py) keeping the KukaLw4?

**Comment by mmmarinho** [comment]
Hello, @marcos-pereira.

An easier way would be just to replace the methods using `DQ_VrepInterface` with the new signatures. 

For example,

```python 
vi.get_joint_positions(joint_handles,VrepInterface.OP_STREAMING)
```
Becomes

```python 
vi.get_joint_positions(joint_names)
```

Note that `joint_handles` are no longer used, nor operating modes such as `OP_STREAMING`.

**Comment by marcos-pereira** [comment]
Hello @mmmarinho , now everything is working. I updated the example and did the pull request.

Thanks for the help!

**Comment by mmmarinho** [comment]
Thanks!
