### ISSUE TITLE
[QUESTION]from dqrobotics.robot_control import DQ_TaskSpacePseudoInverseController, DQ_ClassicQPController, ControlObjective Traceback (most recent call last):   File "<stdin>", line 1, in <module> ImportError: cannot import name 'DQ_TaskSpacePseudoInverseController' from 'dqrobotics.robot_control' (/root/.local/lib/python3.9/site-packages/dqrobotics/robot_control/__init__.py)

### ISSUE THREAD

**Issue by DESEOUMAIGA** [dqrobotics/python-examples#6]
### Acceptance of the Code of Conduct
_Leave these in your question, read, check, and only post if you agree with all of them._ 

I understand that:
- [ ] Support for DQRobotics is given voluntarily and it's not the developers' role to educate and/or convince me of their vision.
- [ ] Any possible response and its timeliness will be based on the relevance, accuracy, and politeness of my request and the following discussion.
- [ ] If a DQRobotics member replies, I must let them know if their response solves my issue or not. 
- [ ] Any suggestion/advice/request I make, as well intentioned as they might be, might not be incorporated into DQRobotics.

### Question

- Could you please let me know if...?
- Would it be possible to...?

**Comment by DESEOUMAIGA** [comment]
How to deal with this python problem？

**Comment by mmmarinho** [comment]
@DESEOUMAIGA 
-----
Thank you for the question.

Unfortunately, the current report you made does not follow the standards expected in bug reports/questions for DQ Robotics.

Please:
1. Read and check the code of conduct.
2. Write a small but descriptive title for your issue.
3. Describe the problem, what were you doing, what you expected, etc in the body of the issue.

This issue will be closed as "stale" until the report fits the standards.
----
