### ISSUE TITLE
[QUESTION] loss module 'DQ_NumericalFilteredPseudoinverseController', 'DQ_TaskSpacePseudoInverseController'...

### ISSUE THREAD

**Issue by DESEOUMAIGA** [dqrobotics/python-examples#7]
![1680087650115](https://user-images.githubusercontent.com/41180688/228513646-68826d17-063c-4da2-bdd9-b0e8de6ebff8.jpg)
While testing the python-examples in Ubuntu system,I found out that there are some modules missing. I tried in mac and ubuntu, both have the same question. Do you know how to fix this bug?

**Comment by mmmarinho** [comment]
@DESEOUMAIGA 

Thank you for the report.

Could you let me know:
1. Which example you ran?
2. What was the output?
3. What Python version you were using?
4. What operating system(s) you tried that on?
5. What version of the DQRobotics library you tried that on?

(Probably related to #6 )

**Comment by DESEOUMAIGA** [comment]
@mmmarinho 

Thanks.

- example: python ./vrep_interface/vrep_interface_move_kuka.py

- output:
Traceback (most recent call last):
  File "./vrep_interface/vrep_interface_move_kuka_and_youbot.py", line 8, in <module>
    from dqrobotics.robot_control import DQ_TaskSpacePseudoInverseController, DQ_ClassicQPController, ControlObjective
ImportError: cannot import name 'DQ_TaskSpacePseudoInverseController' from 'dqrobotics.robot_control' 

- Python version: 3.8.16
-  operating system(s):mac-M1 & Ubuntu 20.04
- DQRobotics library: Mac- 20.4.0.79 & Ubuntu 20.4.0.79

**Comment by mmmarinho** [comment]
@DESEOUMAIGA Thanks!

1. Update the `python-examples` repository with the latest version.
2. Install the dqrobotics package using the `--pre` option, otherwise you'll encounter some other issues.

Example:
```
python3 -m pip uninstall dqrobotics
python3 -m pip install dqrobotics --pre
```

PS: The latest `--pre` version is `dqrobotics-22.10.0a2`
